name: Build and Deploy Sphinx Documentation to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install Java and Graphviz
        run: |
          sudo apt update
          sudo apt install -y default-jre openjdk-17-jdk graphviz

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Auto generate documentation
        run: |
          chmod +x ./refresh_pydoc.sh
          ./refresh_pydoc.sh

      - name: Build documentation
        run: |
          cd docs
          make html

      - name: Upload to GitHub Pages
        id: github-pages
        uses: actions/upload-pages-artifact@v3
        with:
          name: "github-pages"
          path: ${{ github.workspace }}/docs/build/html

  deploy:
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Configure Pages
        uses: actions/configure-pages@v4

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
